Act/urls.py
from django.conf.urls import url
from .views import *
from django.urls import path, re_path

from .views import showNotification
app_name = 'Notification'
urlpatterns = [
    
    re_path(r'^all/$', showNotification,  {'IsFilter': 'all'},name="AllNotification"),
    re_path(r'^l/$', openListNotification, name="NotificationPaginationList"),
    re_path(r'^n/(?P<pk>\d+)/$', openNotificationFullObject, name="NotificationFullForm"),
    re_path(r'^n/$', createNotificationFullObject, name="NotificationFullFormCreate"),
    #re_path(r'^all/', index,  {'IsFilter': 'all'},name="AllNotification"),
    #re_path(r'^month/', index,  {'IsFilter': 'today'},name="ThisMonthNotification"),
    #re_path(r'^a/', api_active, name="api_active"),
    #re_path(r'^c/', api_create, name="api_create"),
    #re_path(r'^u/<int:pk>/', api_update, name="api_update"),
    #re_path(r'^n/c/',      CrudNotification.createNotification, name='createObjectNotification'), 
    #re_path(r'^n/(?P<pk>\d+)/', CrudNotification.updateNotification, name="updateObjectNotification"),
    #re_path(r'^test_pk/(?P<pk>\d+)/', view_test_pk, name="test_pk"),
    #re_path(r'^test_pk_create/', test_pk_create, name="test_pk_create"),
    #re_path(r'^test_page_choose/', test_page_choose, name="test_page_choose"),
    #re_path(r'^test_page_list/', Notification_list_paginator, name="Notification_list_paginator"),
    #re_path(r'^$', index,  {'IsFilter': 'active'},name="activeNotification"),
    

    re_path(r'^ajax/c/a$', api_AddComment,name="apiAddComment"),
    re_path(r'^ajax/a/a$', api_AddAct,name="api_AddAct"),
    re_path(r'^ajax/i/a$', api_AddImage,name="api_AddImage"),
]

Notification2/urls.py
from django.contrib import admin
from django.conf.urls import include,url
from  .main_views import index as local_index

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^s/', include('Act.urls')),
    url(r'^$', local_index,name="index"),
]

from django.conf import settings
from django.conf.urls.static import static
urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/tags/MyTagHeader.html
<nav class="header_nav">
		<h3>Base {% now "Y-m-d H:i:s" %}</h3>
  <ul class="header_ul">
    <li><a class="header_a" href="{% url 'admin:index' %}">admin</a></li>
    <li><a class="header_a" href="{% url 'index' %}">main page</a></li>
	
	<li><span  class="header_a" >Notification ▼</span>
		<ul class="submenu">
			<li><a class="header_a" href="{% url 'Notification:NotificationPaginationList' %}">Список задач</a></li>		
			<li><a class="header_a" href="{% url 'Notification:NotificationFullFormCreate' %}">Новый</a></li>		
	
		</ul>
	</li>


	<li><span class="header_a">Api ▼</span>
		<ul class="submenu">
			
		</ul>
    </li>

	<li><a href="{% url 'Notification:AllNotification' %}" class="header_a" >Все задачи</a></li>
  </ul>
</nav>

templates/tags/MyTagLastAction.html
<div>
    Last update {% now "Y-m-d H:i:s" %}
    <table>
    {% for i in lastLog %}
    <tr class="
        {% if i.is_addition %} tr_log_is_addition {% endif %}
        {% if i.is_change %} tr_log_is_change {% endif %}
        {% if i.is_deletion %} tr_log_is_deletion {% endif %}
        " onclick="document.location = '{{i.get_admin_url}}'">

        <td>{{i.action_time}}</td>
        <td>{{i.object_repr}}</td>
        <td>{{i.user}}</td>        
        <td>{{i.get_action_flag_display}}</td>
        <td>{{i.get_change_message}}</td>
        </a>
    </tr>
    {% endfor %}
    </table>
</div>